---
- hosts: all
  remote_user: dkovalkov
  tasks:

    - name: Setup repository file
      become: yes
      become_method: sudo
      copy:
        src: files/etc/apk/repositories
        dest: /etc/apk/repositories

    - name: Ensure basic packages are installed
      become: yes
      become_method: sudo
      package:
        name={{ item }}
        state=present
      loop:
        - awall
        - htop
        - mtr
        - nano
        - netcat-openbsd
        - procps
        - strace
        - util-linux
        - vim

    - name: Setup resolv.conf file
      become: yes
      become_method: sudo
      copy:
        src: files/etc/resolv.conf
        dest: /etc/resolv.conf

    - name: Setup ntp.conf file
      become: yes
      become_method: sudo
      copy:
        src: files/etc/ntp.conf
        dest: /etc/ntp.conf

    - name: Ensure a job that sync time.
      become: yes
      become_method: sudo
      cron:
        name: "Sync time"
        minute: "0"
        hour: "18"
        job: "ntpd -n -q"

    - name: Ensure that ip_tables module loaded
      become: yes
      become_method: sudo
      modprobe:
        name: ip_tables
        state: present
