---
- hosts: [all]
  remote_user: dkovalkov
  tasks:

    - name: Setup repository file
      become: yes
      become_method: sudo
      copy:
        src: files/etc/apk/repositories
        dest: /etc/apk/repositories

    - name: Ensure basic packages are installed
      become: yes
      become_method: sudo
      package:
        name={{ item }}
        state=present
      loop:
        - vim
        - mtr
        - netcat-openbsd
