---
- hosts: all
  remote_user: dkovalkov
  tasks:

    - name: Setup repository file
      become: yes
      become_method: sudo
      copy:
        src: files/etc/apk/repositories
        dest: /etc/apk/repositories

    - name: Ensure basic packages are installed
      become: yes
      become_method: sudo
      package:
        name={{ item }}
        state=present
      loop:
        - awall
        - htop
        - keepalived
        - mtr
        - nano
        - netcat-openbsd
        - procps
        - strace
        - util-linux
        - vim

    - name: Setup resolv.conf file
      become: yes
      become_method: sudo
      copy:
        src: files/etc/resolv.conf
        dest: /etc/resolv.conf

    - name: Setup ntp.conf file
      become: yes
      become_method: sudo
      copy:
        src: files/etc/ntp.conf
        dest: /etc/ntp.conf

    - name: Add cron task for sync time
      become: yes
      become_method: sudo
      ansible.builtin.copy:
        src: files/etc/periodic/15min/synctime
        dest: /etc/periodic/15min/synctime
        mode: 0755

#      ansible.builtin.cron:
#        name: "Sync time"
#        user: root
#        job: "ntpd -n -q"
#        cron_file: /etc/periodic/15min/synctime

    - name: Ensure that ip_tables module loaded
      become: yes
      become_method: sudo
      modprobe:
        name: ip_tables
        state: present

    - name: Setting sysctl parameters
      become: yes
      become_method: sudo
      ansible.posix.sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        sysctl_file: /etc/sysctl.d/local.conf
        sysctl_set: yes
        state: present
        reload: yes
      with_items:
        - name: "net.ipv4.ip_nonlocal_bind"
          value: 1
        - name: "net.ipv6.conf.all.disable_ipv6"
          value: 1
